name: Build
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/VERSION"
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  build:
    permissions:
      actions: read
      security-events: write
      contents: write
    name: Build (${{ matrix.arch }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build Gnome Pomodoro AppImage
        id: build
        run: |
          sh ./build.sh
      - name: Upload AppImage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gnome-pomodoro-appimage-${{ matrix.arch }}
          retention-days: 7
          path: /tmp/Gnome-Pomodoro*-${{ matrix.arch }}.AppImage*
    outputs:
      VERSION: ${{ steps.build.outputs.VERSION }}

  release:
    name: Release Gnome Pomodoro AppImage (Stable)
    if: ${{ github.ref_name == 'main' }}
    needs:
      - build
    permissions:
      actions: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: gnome-pomodoro-appimage-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: gnome-pomodoro-appimage-x86_64

      - name: Gnome Pomodoro Continous Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          name: "${{ needs.build.outputs.VERSION }}"
          tag_name: ${{ needs.build.outputs.VERSION }}
          target_commitish: ${{ github.sha }}
          files: |
            *.AppImage*
